---
- name: Install httpd Package
  yum: name=httpd state=latest
- name: Create index.html file
  file: path=/var/www/html/index.html state=touch
- name: copy index.html file
  copy: src=/etc/ansible/roles/apache/files/index.html dest=/var/www/html
  notify:
   - restart apache
- name: Start and Enable httpd service
  service: name=httpd state=restarted enabled=yes