---
- hosts: apache
  tasks:
  - name: Install httpd Package
    yum: name=httpd state=latest
  - name: Create index.html file
    file: path=/var/www/html/index.html state=touch
  - name: write content to index.html file
    shell: echo "Welcome to the apache webserver" > /var/www/html/index.html
    notify:
    - restart apache
  - name: Start and Enable httpd service
    service: name=httpd state=restarted enabled=yes
  - name: verify that the web service is running
    command: systemctl status httpd
    register: result
    ignore_errors: True
  - debug: var=result
  handlers:
  - name: restart apache
    service: name=httpd state=restarted
